import streamlit as st
import google.generativeai as genai
import PyPDF2
from pptx import Presentation
import json
import os

# --- Page Configuration ---
st.set_page_config(page_title="AI Lesson Planner", page_icon="📚", layout="centered")

# --- Session State Management ---
# This prevents Streamlit from "forgetting" the generated files when a download button is clicked
if "lesson_plan" not in st.session_state:
    st.session_state.lesson_plan = None
if "slides_file" not in st.session_state:
    st.session_state.slides_file = None

# --- API Key Setup ---
try:
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
    model = genai.GenerativeModel('gemini-2.5-flash')
except KeyError:
    st.warning("API Key not found in Streamlit Secrets!")

# --- Helper Functions ---
def extract_text_from_pdf(uploaded_file):
    text = ""
    try:
        pdf_reader = PyPDF2.PdfReader(uploaded_file)
        for page in pdf_reader.pages:
            text += page.extract_text() + "\n"
    except Exception as e:
        st.error(f"Error reading PDF: {e}")
    return text

def create_slides(json_data, filename="Lesson_Slides.pptx"):
    prs = Presentation()
    try:
        # Load the JSON data generated by the AI
        slides = json.loads(json_data)
        for slide_data in slides:
            # Add a slide with a Title and Content layout
            slide = prs.slides.add_slide(prs.slide_layouts[1]) 
            slide.shapes.title.text = slide_data.get("title", "Slide Title")
            slide.placeholders[1].text = slide_data.get("content", "")
        prs.save(filename)
        return filename
    except Exception as e:
        st.error(f"Failed to build slides: {e}")
        return None

# --- Build the User Interface ---
st.title("📚 AI University Lesson Plan Generator")

col1, col2, col3 = st.columns(3)
with col1:
    week = st.selectbox("Week", range(1, 17))
with col2:
    day = st.selectbox("Day", range(1, 6))
with col3:
    length = st.number_input("Class Length (mins)", min_value=10, max_value=300, value=90)

objective = st.text_input("Lesson Objective", placeholder="e.g., Students will be able to analyze supply and demand curves.")

uploaded_file = st.file_uploader("Upload PDF Materials (Optional)", type="pdf")
material_url = st.text_input("External Link/URL (Optional)")

st.subheader("Activities to Include")
act_col1, act_col2, act_col3, act_col4, act_col5 = st.columns(5)
lecture = act_col1.checkbox("Lecture", value=True)
individual = act_col2.checkbox("Individual activity")
group = act_col3.checkbox("Group activity")
skills = act_col4.checkbox("Skills Check")
assessment = act_col5.checkbox("Assessment")

# --- App Logic & AI Generation ---
if st.button("Generate Lesson Plan & Slides", type="primary"):
    selected_activities = [act for act, selected in zip(
        ["Lecture", "Individual activity", "Group activity", "Skills Check", "Assessment"], 
        [lecture, individual, group, skills, assessment]) if selected]

    if not selected_activities:
        st.error("Please select at least one activity type.")
    elif not objective:
        st.error("Please provide a lesson objective.")
    else:
        with st.spinner("Analyzing materials, writing plan, and building slides (this takes ~15 seconds)..."):
            
            pdf_context = ""
            if uploaded_file is not None:
                pdf_context = extract_text_from_pdf(uploaded_file)
                if len(pdf_context) > 20000: 
                    pdf_context = pdf_context[:20000] + "... [Text Truncated]"

            # 1. Generate the Lesson Plan text
            plan_prompt = f"""
            You are an expert university professor. Create a lesson plan:
            - Timeline: Week {week}, Day {day}
            - Total Length: {length} minutes
            - Objective: {objective}
            - Required Activities: {', '.join(selected_activities)}
            Context: {pdf_context}
            Format clearly with Markdown. Include a chronological schedule.
            """
            
            plan_response = model.generate_content(plan_prompt)
            st.session_state.lesson_plan = plan_response.text

            # 2. Generate the Slides (Forcing JSON Output)
            slide_prompt = f"""
            Based on the following lesson plan, create a 5 to 10 slide presentation outline.
            You MUST output ONLY a valid JSON array of objects.
            Each object must have exactly two keys: "title" (a string) and "content" (a string formatted as bullet points).
            Lesson Plan: {plan_response.text}
            """
            
            # We enforce JSON generation so the python-pptx library can read it safely
            slide_response = model.generate_content(
                slide_prompt,
                generation_config={"response_mime_type": "application/json"}
            )
            
            # 3. Compile the PPTX file
            pptx_path = create_slides(slide_response.text)
            if pptx_path:
                with open(pptx_path, "rb") as f:
                    st.session_state.slides_file = f.read()

# --- Display Results & Downloads ---
if st.session_state.lesson_plan:
    st.markdown("---")
    st.success("Generation Complete!")
    
    # Download Buttons Side-by-Side
    colA, colB = st.columns(2)
    with colA:
        st.download_button(
            label="📄 Download Plan (.md)",
            data=st.session_state.lesson_plan,
            file_name=f"Lesson_Plan_Week_{week}.md",
            mime="text/markdown"
        )
        st.caption("Hint: For a clean PDF, right-click this page and select **Print -> Save as PDF**.")
        
    with colB:
        if st.session_state.slides_file:
            st.download_button(
                label="📊 Download Slides (.pptx)",
                data=st.session_state.slides_file,
                file_name=f"Slides_Week_{week}.pptx",
                mime="application/vnd.openxmlformats-officedocument.presentationml.presentation"
            )
            st.caption("Upload this file to Google Drive to instantly open it as Google Slides.")
            
    st.markdown("---")
    st.markdown(st.session_state.lesson_plan)
